WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-14 01:49:14.009464: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-14 01:49:14.016913: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300035000 Hz
2019-09-14 01:49:14.017889: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55f2ff857770 executing computations on platform Host. Devices:
2019-09-14 01:49:14.017920: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Autoencoder Architecture
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 104, 104, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                22069760  
_________________________________________________________________
sequential_2 (Sequential)    (None, 104, 104, 3)       22053091  
=================================================================
Total params: 44,122,851
Trainable params: 44,111,843
Non-trainable params: 11,008
_________________________________________________________________
None
Discriminator Architecture
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_7 (Dense)              (None, 2704)              89232     
_________________________________________________________________
dense_8 (Dense)              (None, 2704)              7314320   
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 2705      
=================================================================
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras/engine/training.py:493: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
Total params: 14,812,514
Trainable params: 7,406,257
Non-trainable params: 7,406,257
_________________________________________________________________
None
Generator Architecture
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 104, 104, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                22069760  
_________________________________________________________________
sequential_3 (Sequential)    (None, 1)                 7406257   
=================================================================
Total params: 29,476,017
Trainable params: 22,058,752
Non-trainable params: 7,417,265
_________________________________________________________________
None
Found 1083 images belonging to 1 classes.
WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:716: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:724: UserWarning: This ImageDataGenerator specifies `featurewise_std_normalization`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
 1/17 [>.............................] - ETA: 1:29 - loss: 0.1718 - acc: 0.2451 2/17 [==>...........................] - ETA: 53s - loss: 0.1713 - acc: 0.2641  3/17 [====>.........................] - ETA: 39s - loss: 0.1700 - acc: 0.2794 4/17 [======>.......................] - ETA: 32s - loss: 0.1703 - acc: 0.2942 5/17 [=======>......................] - ETA: 27s - loss: 0.1694 - acc: 0.3053 6/17 [=========>....................] - ETA: 23s - loss: 0.1685 - acc: 0.3147 7/17 [===========>..................] - ETA: 20s - loss: 0.1658 - acc: 0.3224 8/17 [=============>................] - ETA: 17s - loss: 0.1628 - acc: 0.3277 9/17 [==============>...............] - ETA: 14s - loss: 0.1586 - acc: 0.330510/17 [================>.............] - ETA: 12s - loss: 0.1539 - acc: 0.330011/17 [==================>...........] - ETA: 10s - loss: 0.1479 - acc: 0.331012/17 [====================>.........] - ETA: 8s - loss: 0.1413 - acc: 0.3346 13/17 [=====================>........] - ETA: 6s - loss: 0.1343 - acc: 0.338314/17 [=======================>......] - ETA: 5s - loss: 0.1277 - acc: 0.339015/17 [=========================>....] - ETA: 3s - loss: 0.1210 - acc: 0.341716/17 [===========================>..] - ETA: 1s - loss: 0.1146 - acc: 0.344117/17 [==============================] - 28s 2s/step - loss: 0.1089 - acc: 0.3485
discriminator_loss = 0.3700356926111614

EPOCH 1 DONE
Epoch 1/1
 1/17 [>.............................] - ETA: 31s - loss: 0.0149 - acc: 0.3738 2/17 [==>...........................] - ETA: 27s - loss: 0.0143 - acc: 0.3816 3/17 [====>.........................] - ETA: 25s - loss: 0.0134 - acc: 0.3938 4/17 [======>.......................] - ETA: 22s - loss: 0.0133 - acc: 0.3957 5/17 [=======>......................] - ETA: 20s - loss: 0.0131 - acc: 0.4048 6/17 [=========>....................] - ETA: 18s - loss: 0.0130 - acc: 0.4138 7/17 [===========>..................] - ETA: 16s - loss: 0.0130 - acc: 0.4209 8/17 [=============>................] - ETA: 14s - loss: 0.0130 - acc: 0.4284 9/17 [==============>...............] - ETA: 12s - loss: 0.0128 - acc: 0.438310/17 [================>.............] - ETA: 10s - loss: 0.0128 - acc: 0.445611/17 [==================>...........] - ETA: 9s - loss: 0.0127 - acc: 0.4559 12/17 [====================>.........] - ETA: 7s - loss: 0.0127 - acc: 0.464513/17 [=====================>........] - ETA: 5s - loss: 0.0126 - acc: 0.473914/17 [=======================>......] - ETA: 4s - loss: 0.0125 - acc: 0.480615/17 [=========================>....] - ETA: 2s - loss: 0.0124 - acc: 0.483616/17 [===========================>..] - ETA: 1s - loss: 0.0123 - acc: 0.490417/17 [==============================] - 25s 1s/step - loss: 0.0122 - acc: 0.4928
Traceback (most recent call last):
  File "aae.py", line 407, in <module>
    adversarial=argsP.adversarial
  File "aae.py", line 232, in train
    discriminator_losses[epoch-1]
IndexError: list index out of range
