WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-09-14 02:02:28.793138: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-09-14 02:02:28.800056: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300035000 Hz
2019-09-14 02:02:28.800710: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55cfd3224890 executing computations on platform Host. Devices:
2019-09-14 02:02:28.800735: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Autoencoder Architecture
Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 104, 104, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                22069760  
_________________________________________________________________
sequential_2 (Sequential)    (None, 104, 104, 3)       22053091  
=================================================================
Total params: 44,122,851
Trainable params: 44,111,843
Non-trainable params: 11,008
_________________________________________________________________
None
Discriminator Architecture
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_7 (Dense)              (None, 2704)              89232     
_________________________________________________________________
dense_8 (Dense)              (None, 2704)              7314320   
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 2705      
=================================================================
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras/engine/training.py:493: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
Total params: 14,812,514
Trainable params: 7,406,257
Non-trainable params: 7,406,257
_________________________________________________________________
None
Generator Architecture
Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 104, 104, 3)       0         
_________________________________________________________________
sequential_1 (Sequential)    (None, 32)                22069760  
_________________________________________________________________
sequential_3 (Sequential)    (None, 1)                 7406257   
=================================================================
Total params: 29,476,017
Trainable params: 22,058,752
Non-trainable params: 7,417,265
_________________________________________________________________
None
Found 1083 images belonging to 1 classes.
WARNING:tensorflow:From /home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/1
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:716: UserWarning: This ImageDataGenerator specifies `featurewise_center`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
/home/aogorodnikov/anaconda3/envs/imgSudoku/lib/python3.7/site-packages/keras_preprocessing/image/image_data_generator.py:724: UserWarning: This ImageDataGenerator specifies `featurewise_std_normalization`, but it hasn't been fit on any training data. Fit it first by calling `.fit(numpy_data)`.
  warnings.warn('This ImageDataGenerator specifies '
 1/17 [>.............................] - ETA: 1:31 - loss: 0.1742 - acc: 0.6433